import Head from 'next/head'

export default function IndividualPost({ data, id }) {
  return (
    <>
      <Head>
        <title>SSR APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className={"pt-8 lg:grid lg:grid-cols-12 lg:gap-8"}>
        <dt className={"text-base font-semibold leading-7 text-gray-900 lg:col-span-5"}>{`Post - ${(parseInt(id)).toString()}`}</dt>
        <dd className={"mt-4 lg:col-span-7 lg:mt-0"}>
          <p className={"text-base leading-7 text-gray-600"}>{data?.data ?? ""}</p>
        </dd>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const { id } = context.params
  const res = await fetch(`https://lorem-ipsum-tau.vercel.app/api/lorem/${id}`)
  const data = await res.json()
  return {
    props: {
      data,
      id,
    }
  }
}