import Head from 'next/head'
import Link from 'next/link'
import { tw } from 'twind'

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>SSR APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className={tw`bg-white`}>
      <div className={tw`mx-auto max-w-7xl divide-y divide-gray-900/10 px-6 py-24 sm:py-32 lg:py-40 lg:px-8`}>
          <h2 className={tw`text-2xl font-bold leading-10 tracking-tight text-gray-900`}>Server side rendered page</h2>
          <dl className={tw`mt-10 space-y-8 divide-y divide-gray-900/10`}>
            {data.map((each, index) => (
              <div key={index.toString()} className={tw`pt-8 lg:grid lg:grid-cols-12 lg:gap-8`}>
                <dt className={tw`text-base font-semibold leading-7 text-gray-900 lg:col-span-5`}>{`Post - ${(index).toString()}`}</dt>
                <dd className={tw`mt-4 lg:col-span-7 lg:mt-0`}>
                  <p className={tw`text-base leading-7 text-gray-600`}>{each}</p>
                  <Link href={`/${index}`} className={tw`text-base font-semibold text-blue-600 hover:text-blue-900`}>
                    Read More
                  </Link>
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://lorem-ipsum-tau.vercel.app/api/lorem')
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}